#!/bin/bash

HOSTNAME=$(hostname)
OS_NAME=$(source /etc/os-release && echo "$NAME $VERSION")
UPTIME=$(uptime -p)

CPU_INFO=$(lshw -class processor | grep "product" | awk -F: '{print $2}')
RAM_SIZE=$(free -h | grep Mem | awk '{print $2}')
DISK_INFO=$(lsblk -o NAME,SIZE,MODEL | grep -v "NAME" | awk '{print $3 " " $2 " " $1}')
VIDEO_CARD=$(lspci | grep VGA)

FQDN=$(hostname -f)
IP_ADDRESS=$(ip a | grep inet | awk '{print $2}' | head -n 1)
GATEWAY_IP=$(ip r | grep default | awk '{print $3}')
DNS_SERVER=$(cat /etc/resolv.conf | grep nameserver | awk '{print $2}')

LOGGED_IN_USERS=$(who | awk '{print $1}' | sort | uniq | tr '\n' ',')
DISK_SPACE=$(df -h | grep '/$' | awk '{print $4}')
PROCESS_COUNT=$(ps aux | wc -l)
LOAD_AVERAGES=$(uptime | awk -F'load average:' '{print $2}' | cut -d, -f1-3)
LISTENING_PORTS=$(ss -tuln | wc -l)
UFW_STATUS=$(sudo ufw status | head -n 1 | awk '{print $2}')

echo ""
echo "System Report generated by $USER, $(date)"
echo ""
echo "System Information"
echo "------------------"
echo "Hostname: $HOSTNAME"
echo "OS: $OS_NAME"
echo "Uptime: $UPTIME"
echo ""
echo "Hardware Information"
echo "--------------------"
echo "CPU: $CPU_INFO"
echo "RAM: $RAM_SIZE"
echo "Disk(s): $DISK_INFO"
echo "Video: $VIDEO_CARD"
echo ""
echo "Network Information"
echo "-------------------"
echo "FQDN: $FQDN"
echo "Host Address: $IP_ADDRESS"
echo "Gateway IP: $GATEWAY_IP"
echo "DNS Server: $DNS_SERVER"
echo ""
echo "System Status"
echo "-------------"
echo "Users Logged In: $LOGGED_IN_USERS"
echo "Disk Space: $DISK_SPACE"
echo "Process Count: $PROCESS_COUNT"
echo "Load Averages: $LOAD_AVERAGES"
echo "Listening Network Ports: $LISTENING_PORTS"
echo "UFW Status: $UFW_STATUS"
echo ""
